name: "face_detector"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "input.1"
    data_type: TYPE_FP32
    dims: [ 1, 3, 640, 640 ]
  }
]
output [
  {
    name: "448"
    data_type: TYPE_FP32
    dims: [ 12800, 1 ]
  },
  {
    name: "451"
    data_type: TYPE_FP32
    dims: [ 12800, 4 ] # Updated this
  },
  {
    name: "454"
    data_type: TYPE_FP32
    dims: [ 12800, 10 ] # Updated this to 10
  }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]